/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.vista;

public class FRM_About extends javax.swing.JFrame {

    /**
     * Creates new form FRM_About
     */
    public FRM_About() {
        this.setUndecorated(true);
        initComponents();
        jTextPane2.setText("Daniela Garcia Campos C23120\n" +
"Jose Alejandro Garita Monge C23193\n" +
"Sara Benavides Murillo C31089\n" +
"\n" +
"El proyecto significa para el equipo una idea innovadora para optimizar las transacciones de la Biblioteca, es una herramienta informática que facilita tanto el acceso como la administración de los recursos que la misma ofrece, en ámbitos como la mejora de la gestión Bibliotecarias, incluyendo aspectos como la eficiencia en el control de inventario y en la automatización de procesos, la facilitación del acceso a la información, así como obtener información actualizada y que esta incluya una búsqueda rápida y precisa\n" +
"\n" +
"La principal razón de la creación del proyecto es cómo este sistema transaccional va a mejorar notablemente la vida de los estudiantes y de los bibliotecarios, los estudiantes van a tener el beneficio de obtener un acceso más eficientes a los recursos educativos y así mejorar su rendimiento académico, la posibilidad de buscar libros en línea ahorrará tiempo a los estudiantes y además creará un mayor interés en la búsqueda de libros para su desarrollo personal y académico. También el personal bibliotecario se verá beneficiado ya que el proyecto hará que se reduzca la carga de trabajo y facilitará la planificación y la toma de decisiones.");

        this.setSize(560, 360);
        this.setLocationRelativeTo(null);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jTextPane2.setEditable(false);
        jScrollPane2.setViewportView(jTextPane2);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jButton1.setText("Salir");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
