/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.vista;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import ucr.ac.cr.modelo.Prestamo;
import ucr.ac.cr.modelo.Registro_Prestamo;

/**
 *
 * @author danig
 */
public class FRM_Prestamo extends javax.swing.JFrame {

    private String dateSolicitado;
    private String dateEntrega;

    /**
     * Creates new form FRM_Prestamo
     */
    public FRM_Prestamo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void escuchadorMenu(ActionListener manejador) {
        agregar.addActionListener(manejador);
        modificar.addActionListener(manejador);
        eliminar.addActionListener(manejador);
        buscar.addActionListener(manejador);
        Salir.addActionListener(manejador);
    } //Fin del metodo 

    public void actualizarListaPrestamoATabla(Registro_Prestamo registro_Prestamo) {
        DefaultTableModel modeloTabla = (DefaultTableModel) jTable1.getModel();

        if (registro_Prestamo.getListaPrestamos().isEmpty()) {
            modeloTabla.setRowCount(0); // Limpiar la tabla si no hay préstamos
        } else {
            modeloTabla.setRowCount(0); // Limpiar la tabla antes de agregar nuevos préstamos

            for (Prestamo prestamo : registro_Prestamo.getListaPrestamos()) {
                Object[] fila = {
                    prestamo.getId(),
                    prestamo.getCarnet(),
                    prestamo.getLibro_Solicitidos(),
                    prestamo.getFecha_Inicio(),
                    prestamo.getFecha_fin()
                };
                modeloTabla.addRow(fila);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        eliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtCarnet = new javax.swing.JTextField();
        registroEstudiantes = new javax.swing.JLabel();
        comboLibros = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSolicitado = new javax.swing.JButton();
        jFechaEntrega = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregar.setBackground(new java.awt.Color(204, 255, 204));
        agregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregar.setText("Agregar");
        getContentPane().add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, -1, -1));

        modificar.setBackground(new java.awt.Color(204, 255, 204));
        modificar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Carnet");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        eliminar.setBackground(new java.awt.Color(204, 255, 204));
        eliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eliminar.setText("Eliminar");
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("Fecha solicitado ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        buscar.setBackground(new java.awt.Color(204, 255, 204));
        buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buscar.setText("Buscar");
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, -1, -1));

        Salir.setBackground(new java.awt.Color(204, 255, 204));
        Salir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Salir.setText("Salir");
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("Libro Solicitado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtId.setBackground(new java.awt.Color(255, 204, 204));
        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 43, -1));

        txtCarnet.setBackground(new java.awt.Color(255, 204, 204));
        txtCarnet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtCarnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 102, -1));

        registroEstudiantes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        registroEstudiantes.setForeground(new java.awt.Color(255, 153, 153));
        registroEstudiantes.setText("Registro Prestamo");
        getContentPane().add(registroEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        comboLibros.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(comboLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 123, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("Fecha Entrega");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Carnet", "Libro Solicitado", "Fecha Entrega", "Fecha Solicitado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 660, 250));

        jSolicitado.setBackground(new java.awt.Color(255, 204, 204));
        jSolicitado.setForeground(new java.awt.Color(255, 255, 255));
        jSolicitado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccionar  fecha y hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jSolicitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSolicitadoActionPerformed(evt);
            }
        });
        getContentPane().add(jSolicitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 150, 30));

        jFechaEntrega.setBackground(new java.awt.Color(255, 204, 204));
        jFechaEntrega.setForeground(new java.awt.Color(255, 255, 255));
        jFechaEntrega.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seleccionar  fecha y hora", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jFechaEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFechaEntregaActionPerformed(evt);
            }
        });
        getContentPane().add(jFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 150, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void jSolicitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSolicitadoActionPerformed
        // TODO add your handling code here:
        // Mostrar el diálogo para seleccionar la fecha y la hora
        SeleccionFechaHora seleccionFechaHora = new SeleccionFechaHora(fechaHora -> {
            // Obtener la fecha y la hora seleccionadas desde el diálogo y realizar las operaciones necesarias
            dateSolicitado = fechaHora;
            jSolicitado.setText(dateSolicitado); // Establecer el texto del botón con la fecha y la hora seleccionadas
        });
    }//GEN-LAST:event_jSolicitadoActionPerformed

    private void jFechaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFechaEntregaActionPerformed
        // TODO add your handling code here:
        // Mostrar el diálogo para seleccionar la fecha y la hora
        SeleccionFechaHora seleccionFechaHora = new SeleccionFechaHora(fechaHora -> {
            // Obtener la fecha y la hora seleccionadas desde el diálogo y realizar las operaciones necesarias
            dateEntrega = fechaHora;
            jFechaEntrega.setText(dateEntrega); // Establecer el texto del botón con la fecha y la hora seleccionadas
        });
    }//GEN-LAST:event_jFechaEntregaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_Prestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JButton agregar;
    private javax.swing.JButton buscar;
    private javax.swing.JComboBox<String> comboLibros;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton jFechaEntrega;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSolicitado;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificar;
    private javax.swing.JLabel registroEstudiantes;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtCarnet() {
        return txtCarnet;
    }

    public void setTxtCarnet(JTextField txtCarnet) {
        this.txtCarnet = txtCarnet;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    public JComboBox<String> getComboLibros() {
        return comboLibros;
    }

    public void setComboLibros(JComboBox<String> comboLibros) {
        this.comboLibros = comboLibros;
    }

    public JButton getjFechaEntrega() {
        return jFechaEntrega;
    }

    public void setjFechaEntrega(JButton jFechaEntrega) {
        this.jFechaEntrega = jFechaEntrega;
    }

    public JButton getjSolicitado() {
        return jSolicitado;
    }

    public void setjSolicitado(JButton jSolicitado) {
        this.jSolicitado = jSolicitado;
    }



}
