/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.vista;

import java.awt.event.ActionListener;
import javax.swing.JLabel;

/**
 *
 * @author danig
 */
public class FRM_Menu extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Menu
     */
    public FRM_Menu(String rol) {
        initComponents();
        this.setLocationRelativeTo(null);

        if (rol.equals("Estudiante")) {
            jmiRegistroBibliotecario.setVisible(false);
            jmiRegistroEstudiantes.setVisible(false);
            jmiRegistroLibros.setVisible(false);
        }
    }

    public FRM_Menu() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    public void escuchadorMenu(ActionListener manejador) {
        jmiRegistroEstudiantes.addActionListener(manejador);
        jmiRegistroLibros.addActionListener(manejador);
        jmiRegistroPrestamos.addActionListener(manejador);
        jmiRegistroBibliotecario.addActionListener(manejador);
        jmiSalir.addActionListener(manejador);
    } //Fin del metodo 

    public JLabel getjRol() {
        return jRol;
    }

    public void setjRol(JLabel jRol) {
        this.jRol = jRol;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jRol = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jmiRegistroLibros = new javax.swing.JMenuItem();
        jmiRegistroEstudiantes = new javax.swing.JMenuItem();
        jmiRegistroPrestamos = new javax.swing.JMenuItem();
        jmiRegistroBibliotecario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jLabel1.setFont(new java.awt.Font("Broadway", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Biblioteca Universitaria");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRol.setFont(new java.awt.Font("Lucida Console", 0, 48)); // NOI18N
        jRol.setForeground(new java.awt.Color(255, 204, 204));

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("BIBLIOTECA UNIVERSITARIA");

        jMenu3.setText("Modulos");

        jmiRegistroLibros.setText("Registro Libros");
        jMenu3.add(jmiRegistroLibros);

        jmiRegistroEstudiantes.setText("Registro Estudiantes");
        jMenu3.add(jmiRegistroEstudiantes);

        jmiRegistroPrestamos.setText("Registro Prestamos");
        jMenu3.add(jmiRegistroPrestamos);

        jmiRegistroBibliotecario.setText("Registro Bibliotecarios");
        jMenu3.add(jmiRegistroBibliotecario);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");

        jmiSalir.setText("Salir");
        jMenu4.add(jmiSalir);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRol, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(95, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(67, 67, 67)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addComponent(jRol, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(131, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(121, 121, 121)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jRol;
    private javax.swing.JMenuItem jmiRegistroBibliotecario;
    private javax.swing.JMenuItem jmiRegistroEstudiantes;
    private javax.swing.JMenuItem jmiRegistroLibros;
    private javax.swing.JMenuItem jmiRegistroPrestamos;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
} //Fin de la clase 
